export const countryCodes = [
	// America
	{name: 'Argentina', dial_code: '+54', code: 'AR'},
	{name: 'Bolivia', dial_code: '+591', code: 'BO'},
	{name: 'Brazil', dial_code: '+55', code: 'BR'},
	{name: 'United States', dial_code: '+1', code: 'US'},
	{name: 'Chile', dial_code: '+56', code: 'CL'},
	{name: 'Colombia', dial_code: '+57', code: 'CO'},
	{name: 'Costa Rica', dial_code: '+506', code: 'CR'},
	{name: 'Dominican Republic', dial_code: '+1849', code: 'DO'},
	{name: 'Ecuador', dial_code: '+593', code: 'EC'},
	{name: 'El Salvador', dial_code: '+503', code: 'SV'},
	{name: 'Guatemala', dial_code: '+502', code: 'GT'},
	{name: 'Honduras', dial_code: '+504', code: 'HN'},
	{name: 'Mexico', dial_code: '+52', code: 'MX'},
	{name: 'Nicaragua', dial_code: '+505', code: 'NI'},
	{name: 'Panama', dial_code: '+507', code: 'PA'},
	{name: 'Paraguay', dial_code: '+595', code: 'PY'},
	{name: 'Peru', dial_code: '+51', code: 'PE'},
	{name: 'Puerto Rico', dial_code: '+1939', code: 'PR'},
	{name: 'Uruguay', dial_code: '+598', code: 'UY'},
	{name: 'Venezuela', dial_code: '+58', code: 'VE'},
	// Europe
	{name: 'Andorra', dial_code: '+376', code: 'AD'},
	{name: 'Austria', dial_code: '+43', code: 'AT'},
	{name: 'Belgium', dial_code: '+32', code: 'BE'},
	{name: 'Bulgaria', dial_code: '+359', code: 'BG'},
	{name: 'Croatia', dial_code: '+385', code: 'HR'},
	{name: 'Cyprus', dial_code: '+357', code: 'CY'},
	{name: 'Czech Republic', dial_code: '+420', code: 'CZ'},
	{name: 'Denmark', dial_code: '+45', code: 'DK'},
	{name: 'Estonia', dial_code: '+372', code: 'EE'},
	{name: 'Finland', dial_code: '+358', code: 'FI'},
	{name: 'France', dial_code: '+33', code: 'FR'},
	{name: 'Germany', dial_code: '+49', code: 'DE'},
	{name: 'Greece', dial_code: '+30', code: 'GR'},
	{name: 'Hungary', dial_code: '+36', code: 'HU'},
	{name: 'Iceland', dial_code: '+354', code: 'IS'},
	{name: 'Ireland', dial_code: '+353', code: 'IE'},
	{name: 'Italy', dial_code: '+39', code: 'IT'},
	{name: 'Latvia', dial_code: '+371', code: 'LV'},
	{name: 'Liechtenstein', dial_code: '+423', code: 'LI'},
	{name: 'Lithuania', dial_code: '+370', code: 'LT'},
	{name: 'Luxembourg', dial_code: '+352', code: 'LU'},
	{name: 'Malta', dial_code: '+356', code: 'MT'},
	{name: 'Monaco', dial_code: '+377', code: 'MC'},
	{name: 'Netherlands', dial_code: '+31', code: 'NL'},
	{name: 'Norway', dial_code: '+47', code: 'NO'},
	{name: 'Poland', dial_code: '+48', code: 'PL'},
	{name: 'Portugal', dial_code: '+351', code: 'PT'},
	{name: 'Romania', dial_code: '+40', code: 'RO'},
	{name: 'Russia', dial_code: '+7', code: 'RU'},
	{name: 'San Marino', dial_code: '+378', code: 'SM'},
	{name: 'Slovakia', dial_code: '+421', code: 'SK'},
	{name: 'Slovenia', dial_code: '+386', code: 'SI'},
	{name: 'Spain', dial_code: '+34', code: 'ES'},
	{name: 'Sweden', dial_code: '+46', code: 'SE'},
	{name: 'Switzerland', dial_code: '+41', code: 'CH'},
	{name: 'Ukraine', dial_code: '+380', code: 'UA'},
	{name: 'United Kingdom', dial_code: '+44', code: 'GB'},
];
