
/**
 * Este archivo contiene las Cloud Functions relacionadas con la generación
 * de reportes para los administradores.
 */

import {onCall, HttpsError} from "firebase-functions/v2/https";
import * as logger from "firebase-functions/logger";
import * as admin from "firebase-admin";
import {Parser} from "json2csv";
import type { Order } from "./types";


/**
 * Función "Callable" para generar un reporte de ventas en formato CSV.
 * Solo los administradores pueden llamar a esta función.
 * @param {object} request - Objeto de la solicitud callable.
 * @return {object} - Un objeto con el contenido del CSV en base64.
 */
export const generateSalesReport = onCall(async (request) => {
  // 1. Verificación de Autenticación y Rol de Administrador
  if (!request.auth || request.auth.token?.role !== "admin") {
    logger.error("Unauthorized attempt to generate sales report.");
    throw new HttpsError(
      "permission-denied",
      "Solo los administradores pueden generar reportes.",
    );
  }

  try {
    const firestore = admin.firestore();

    // Usar la colección raíz 'orders'
    const ordersSnapshot = await firestore.collection("orders")
      .orderBy("purchaseDate", "desc").get();

    if (ordersSnapshot.empty) {
      logger.info("No orders found to generate a report.");
      return {csv: ""};
    }

    const reportData = ordersSnapshot.docs.map((doc) => {
      const order = doc.data() as Order;
      
      // Aplanar los datos para el CSV
      const firstTicket = order.tickets[0] || {};
      const ticketDescription = firstTicket.tierName 
        ? `${firstTicket.quantity} x ${firstTicket.tierName}` 
        : `${order.tickets.length} x Asiento(s) (${firstTicket.section || 'N/A'})`;


      return {
        orderId: doc.id,
        userId: order.userId,
        presentationId: order.presentationId,
        totalPrice: order.totalPrice,
        currency: order.currency,
        purchaseDate: order.purchaseDate?.toDate()?.toISOString() || "",
        ticketDetails: ticketDescription,
      };
    });

    const fields = [
      "orderId",
      "userId",
      "presentationId",
      "totalPrice",
      "currency",
      "purchaseDate",
      "ticketDetails",
    ];

    const json2csvParser = new Parser({fields});
    const csv = json2csvParser.parse(reportData);

    logger.log(`Sales report generated by admin: ${request.auth.uid}`);

    // Devolvemos el CSV como un string en base64
    return {csv: Buffer.from(csv).toString("base64")};
  } catch (error) {
    logger.error(
      `Error generating sales report for admin ${request.auth.uid}:`,
      error,
    );
    if (error instanceof HttpsError) {
      throw error;
    }
    throw new HttpsError(
      "internal",
      "Ocurrió un error al generar el reporte de ventas.",
    );
  }
});
